"""added crypto table

Revision ID: 140987dd8c27
Revises: 2af5f80db887
Create Date: 2022-03-13 17:45:25.153936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '140987dd8c27'
down_revision = '2af5f80db887'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crypto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('number_of_coins', sa.Float(), nullable=True),
    sa.Column('cost_per_coin', sa.Float(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crypto_id'), 'crypto', ['id'], unique=False)
    op.create_index(op.f('ix_crypto_symbol'), 'crypto', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crypto_symbol'), table_name='crypto')
    op.drop_index(op.f('ix_crypto_id'), table_name='crypto')
    op.drop_table('crypto')
    # ### end Alembic commands ###
