"""updated stock attributes

Revision ID: 2af5f80db887
Revises: 13ef9df02e61
Create Date: 2022-03-11 15:59:17.664228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2af5f80db887'
down_revision = '13ef9df02e61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock', sa.Column('ticker', sa.String(), nullable=True))
    op.add_column('stock', sa.Column('company_name', sa.String(), nullable=True))
    op.add_column('stock', sa.Column('number_of_shares', sa.Float(), nullable=True))
    op.add_column('stock', sa.Column('cost_per_share', sa.Float(), nullable=True))
    op.drop_index('ix_stock_description', table_name='stock')
    op.drop_index('ix_stock_title', table_name='stock')
    op.create_index(op.f('ix_stock_company_name'), 'stock', ['company_name'], unique=False)
    op.create_index(op.f('ix_stock_ticker'), 'stock', ['ticker'], unique=False)
    op.drop_constraint('stock_owner_id_fkey', 'stock', type_='foreignkey')
    op.create_foreign_key(None, 'stock', 'user', ['owner_id'], ['id'], ondelete='CASCADE')
    op.drop_column('stock', 'title')
    op.drop_column('stock', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('stock', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'stock', type_='foreignkey')
    op.create_foreign_key('stock_owner_id_fkey', 'stock', 'user', ['owner_id'], ['id'])
    op.drop_index(op.f('ix_stock_ticker'), table_name='stock')
    op.drop_index(op.f('ix_stock_company_name'), table_name='stock')
    op.create_index('ix_stock_title', 'stock', ['title'], unique=False)
    op.create_index('ix_stock_description', 'stock', ['description'], unique=False)
    op.drop_column('stock', 'cost_per_share')
    op.drop_column('stock', 'number_of_shares')
    op.drop_column('stock', 'company_name')
    op.drop_column('stock', 'ticker')
    # ### end Alembic commands ###
